<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Novo Logradouro           
        </div>
    </div>
    <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('logradouros', array('action' => 'adicionar')); ?>">
        <div class="panel-body">
            <div class="form-group">
                <label for="inputNome" class="col-lg-3 col-md-3 control-label">Nome:</label>
                <div class="col-lg-9 col-md-9">
                    <input type="text" name="nome" class="form-control" id="inputNome" placeholder="Nome Logradouro">
                </div>
            </div>

            <div class="form-group">
                <label for="inputCidCodigo" class="col-lg-3 col-md-3 control-label">Cidade:</label>
                <div class="col-lg-9  col-md-9">
                    <input type="text" name="cidcodigo" class="form-control" id="inputTelefonePrincipal" placeholder="Cidade à qual pertence este logradouro">
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-primary">Salvar</button>
            <a href="<?php echo $this->url('logradouros'); ?>" class="btn btn-default">Voltar</a>
        </div>
    </form>
</div>